

normal: 
	cd syrup/parallel; make normal; mkdir -p ../../bin; cp glucose-syrup_release ../../bin/glucose-syrup

cluster: 
	cd syrup/parallel; make cluster; mkdir -p ../../bin; cp glucose-syrup_release ../../bin/glucose-syrup

debugNormal:
	cd syrup/parallel; make debugNormal; mkdir -p ../../bin; cp glucose-syrup_debug ../../bin/glucose-syrup

debugCluster: 
	cd syrup/parallel; make debugCluster; mkdir -p ../../bin; cp glucose-syrup_debug ../../bin/glucose-syrup

clean: 
	cd syrup/parallel; make allclean
	rm -rf bin/*

